version: '3.1'

services:

  mongo:
    image: mongo:4.4.13
    container_name: ${DOCKER_CONTAINER_MONGO_NAME}
    restart: unless-stopped
    volumes:
      - ./mongo_data:/data/db
      - ./backups:/backups
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - ${DOCKER_CONTAINER_MONGO_PORT}:27017

  mongo-express:
    image: mongo-express
    container_name: ${DOCKER_CONTAINER_MONGO_EXPRESS_NAME}
    restart: unless-stopped
    ports:
      - ${DOCKER_CONTAINER_MONGO_EXPRESS_PORT}:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${DOCKER_CONTAINER_MONGO_NAME}:${DOCKER_CONTAINER_MONGO_PORT}
